config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :orders
  end
  resources :events do
    resources :orders
  end

  root 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :orders
	has_many :users, through: :orders
	self.inheritance_column = :sti_type
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :event
	self.inheritance_column = :sti_type
	
	validates :shares, presence: true
	validates :shares, numericality: { only_integer: true }
	validates :price, presence: true
	validates :price, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :events, through: :orders     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
  	@event = Event.new
  end

  def index
  	@events = Event.all

  	@bidask = @events.map {|event|
  		buyorders  = event.orders.select{|x| (x.type == "buy")  && (x.shares - x.filled > 0)}
  		sellorders = event.orders.select{|x| (x.type == "sell") && (x.shares - x.filled > 0)}
  		bid = nil
  		if buyorders.length > 0 
  		    bid = buyorders.sort{ |x, y| x.price <=> y.price }.last.price
  		end
  		ask = nil
  		if sellorders.length > 0
  			ask = sellorders.sort{ |x, y| x.price <=> y.price }.first.price
  		end
  		{event_id: event.id, bid: bid, ask: ask}
  	}
  end

  def show 
  	@event = Event.find(params[:id])
  	@orders = @event.orders.select{ |x| x.filled < x.shares }.sort{ |x, y| y.price <=> x.price }
  end

  private
  def get_bidask(event)

  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def new
  	@order = Order.new
  end

  def index
    @user = User.find(params[:user_id])
  	@orders = @user.orders.order('event_id, created_at')
    @orders.each { |x|
      puts "Event #{x.event.name} Price #{x.price} Shares #{x.shares}"
    }
  end
  
  def show
    @order = Order.find(params[:id])
    puts @order
  end

  def create
  	@order = Order.new(order_params)
    @order.user_id = current_user.id
    @order.event_id = params[:event_id]
    @order.filled = fill_order(params[:event_id], @order.type, @order.price, @order.shares)

    @order.save

    redirect_to action: 'show', id: @order.id
  end

  private
  def order_params
    params.require(:order).permit(:price, :shares, :type)
  end

  def fill_order(event_id, type, price, shares)
    match_type = {"buy" => "sell", "sell" => "buy" }[type]
    price_comp = {"buy" => "<=",   "sell" => ">="  }[type]
    sort_order = {"buy" => "ASC",  "sell" => "DESC"}[type]
    @matching_orders = 
      Order.where(
        "event_id = ? AND type = ? AND price #{price_comp} ?", event_id, match_type, price
      ).order(
        "price #{sort_order}, created_at DESC")

    shares_filled = 0
    @matching_orders.each { |order| 
      puts "Price #{order.price} Shares #{order.shares} Filled #{order.filled}"
      puts "Shares to fill #{shares}, already filled #{shares_filled}"  
      if shares <= 0 then break end
      unfilled_shares = order.shares - order.filled
      if(shares >= unfilled_shares)
        shares -= unfilled_shares
        order.filled = order.shares # == order.filled += unfilled_shares
        shares_filled += unfilled_shares
      else #shares < unfilled_shares
        order.filled += shares
        shares_filled += shares
        shares -= unfilled_shares
      end
      puts "Saving Order.Filled #{order.filled}"
      order.save
    }
    puts "Returning shares_filled #{shares_filled}"
    shares_filled
    # find all opposite orders with bid > ask
    # count and fill number of shares
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<table cellpadding = "5">
  <tbody>
  	  <tr>
  	  	<td align = 'center'> Event </td>
  	  	<td align = 'center'> Bid </td>
  	  	<td align = 'center'> / </td>
  	  	<td align = 'center'> Ask </td>
  	  	<td align = 'center' colspan = 2> Actions </td>
  	<% @events.each do |event| %>
  	  <tr>
        <td><%= link_to event.name, event_path(event) %></td>
            <% bidask = @bidask.select{|x| x[:event_id] == event.id}.first %>
        <td><%= bidask[:bid] %></td><td> / </td><td><%= bidask[:ask] %></td>
        <td><%= link_to 'Sell', new_event_order_path(event, type: "sell") %></td>
        <td><%= link_to 'Buy',  new_event_order_path(event, type: "buy")  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><%= link_to "My Orders", user_orders_path(current_user) %>

app/views/events/show.html.erb
<%= @event.name %>
<table cellpadding="5">
  <tbody>
  	<tr>
      <td align = "center" colspan = 3><%= link_to 'Sell Shares',  new_event_order_path(@event, type: "sell")  %></td>
      <td align = "center" colspan = 3><%= link_to 'Buy Shares', new_event_order_path(@event, type: "buy") %></td>
  	</tr>
  	<tr>
  	  <td align = "center" colspan = 3> Ask </td>
  	  <td align = "center" colspan = 3> Bid </td>
    </tr>
  	<% @orders.each do |order| %>
  	  <% if order.filled == order.shares then next end %> 
  	  <% if order.type == "sell" %>
  	    <tr>
  	  	  <td>$<%= order.price %></td>
  	  	  <td> x </td>
  	  	  <td><%= order.shares - order.filled %></td>
  	  	  <td colspan = 3></td>
  	    </tr>
  	  <% else %>
  	    <tr>
  	      <td colspan = 3></td>
  	  	  <td>$<%= order.price %></td>
  	  	  <td> x </td>
  	  	  <td><%= order.shares - order.filled %></td>
  	    </tr>
  	  <% end %>
  	<% end %>
  </tbody>
</table>
<br><%= link_to "All Events", events_path %> <%= link_to "My Orders", user_orders_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intrade</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<table>
  <tbody>

  	<tr><td colspan = 5> Open Orders </td></tr>
  	<% @orders.select{|x| x.filled != x.shares}.each do |order| %>
  	  <tr>
        <td><%= link_to order.event.name, event_path(order.event) %></td>
        <td><%= order.type.capitalize %></td>
        <td><%= order.shares %> Shares </td>
        <td>@ $<%= order.price %></td>
        <td>(<%= order.filled %> Shares Filled)</td>
      </tr>
    <% end %>

    <tr><td colspan = 5> Completed Orders </td></tr>
  	<% @orders.select{|x| x.filled == x.shares}.each do |order| %>
  	  <tr>
        <td><%= link_to order.event.name, event_path(order.event) %></td>
        <td><%= order.type.capitalize %></td>
        <td><%= order.shares %> Shares </td>
        <td>@ $<%= order.price %></td>
        <td></td>
      </tr>
    <% end %>

  </tbody>
</table>
<br><%= link_to "All Events", events_path %>

app/views/orders/new.html.erb
<%= form_for([:event, @order]) do |f| %>

  <div class="field">
  	<%= f.label :price %><br>
  	<%= f.number_field :price, min: 0, max: 10, step: 0.05, required: true %>
  </div>
  <div class="field">
  	<%= f.label :shares %><br>
  	<%= f.number_field :shares, min: 0, required: true %>
  </div>
  <%= f.hidden_field :type, value: params[:type] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<%end %>
<%= link_to "Cancel", :back %>

app/views/orders/show.html.erb
<table>
  <tbody>
  	  <tr>
        <td><%= @order.type.capitalize %> <%= @order.event.name %> <%= @order.shares %> @ <%= @order.price%></td>
      </tr>
      <% if @order.filled > 0 %>
      <tr>
      	<td><%= @order.filled %> shares were filled </td>
      </tr>
      <% end %>
  </tbody>
</table>
<%= link_to "Back to event", event_path(@order.event) %> <p>
<%= link_to "All Events", events_path %> <%= link_to "My Orders", user_orders_path(current_user) %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>